apiVersion: v1
kind: Service
metadata:
  name: fatboy-slim-service
  namespace: fatboy-staging
  labels:
    run: fatboy-slim-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: web
  selector:
    app: fatboy-slim
  type: LoadBalancer