version: "3.9"
services:
  fatboy-slim-wop:
    container_name: fatboy-slim-wop
    build: .
    ports:
      - 5000:5000
    environment:
      DB_SCHEMA: weapon_of_choice
      DB_USER: fatboyslim
      DB_PASSWORD: wop
      DB_HOST: postgres
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    restart: always 
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: weapon_of_choice
      POSTGRES_USER: fatboyslim
      POSTGRES_PASSWORD: wop
      POSTGRES_HOST: master_postgres