app:
  port: 5000
  assets:
    path: 'public'
    templateContentPath: '/content'
  session:
    secretKey: secret
db:
  secretKey: qwertyuiopasdfghjklzxcvbnm
  username: 'fatboyslim'
  password: 'wop'
  database: 'weapon_of_choice'
  host: 'localhost'
  dialect: 'postgres'
